---
namespace: kevingstewart
name: f5_sslo_ansible
authors:
- Kevin Stewart <kevin.g.stewart@gmail.com>
description: Ansible automation modules for F5 BIG-IP SSL Orchestrator
dependencies:
  "f5networks.f5_modules": ">=1.9.0"
license_file: LICENSE
readme: README.md
repository: https://github.com/kevingstewart/f5_sslo_ansible
issues: https://github.com/kevingstewart/f5_sslo_ansible/issues
tags:
  - f5
  - sslo
  - ssl orchestrator
version: 1.0.0
build_ignore:
  - .gitignore

