---

- name: SSLO Utility Functions
  hosts: localhost
  gather_facts: False
  connection: local

  collections:
    - kevingstewart.f5_sslo_ansible

  vars: 
    provider:
      server: 10.1.1.4
      user: admin
      password: admin
      validate_certs: no
      server_port: 443

  tasks:
    - name: SSLO Utility Functions
      bigip_sslo_config_utility:
        provider: "{{ provider }}"
        
        utility: delete-all

      delegate_to: localhost