---

- name: Create SSLO DNS resolver
  hosts: localhost
  gather_facts: False
  connection: local

  collections:
    - kevingstewart.f5_sslo_ansible

  vars: 
    provider:
      server: 192.16.1.77
      user: admin
      password: admin
      validate_certs: no
      server_port: 443

  tasks:
    - name: SSLO dns resolver
      bigip_sslo_config_resolver:
        provider: "{{ provider }}"
        forwardingNameservers:
          - "10.1.20.1"
        mode: output
      delegate_to: localhost