---

- name: Create SSLO service(s)
  hosts: localhost
  gather_facts: False
  connection: local
  
  collections:
    - kevingstewart.f5_sslo_ansible

  vars: 
    provider:
      server: 10.1.1.4
      user: admin
      password: admin
      validate_certs: no
      server_port: 443

  tasks:
    - name: SSLO HTTP service
      bigip_sslo_service_http:
        provider: "{{ provider }}"
        name: "http_1"
        devicesTo:
          interface: "1.3"
          tag: 30
          selfIp: "198.19.96.7"
          netmask: "255.255.255.128"
        devicesFrom:
          interface: "1.3"
          tag: 40
          selfIp: "198.19.96.245"
          netmask: "255.255.255.128"
        devices: 
          - ip: "198.19.96.30"
            port: 3128
      delegate_to: localhost