---

- name: Create SSLO service(s)
  hosts: localhost
  gather_facts: False
  connection: local

  collections:
    - kevingstewart.f5_sslo_ansible
  
  vars: 
    provider:
      server: 172.16.1.77
      user: admin
      password: admin
      validate_certs: no
      server_port: 443

  tasks:
    - name: SSLO TAP service
      bigip_sslo_service_tap:
        provider: "{{ provider }}"
        name: "tap_1"
        devices: 
            interface: "1.6"
        macAddress: "12:12:12:12:12:12"
        mode: output
      register: tapservice
      delegate_to: localhost
    
    - debug:
        msg: "{{ tapservice }}"