---

- name: Create SSLO service(s)
  hosts: localhost
  gather_facts: False
  connection: local

  collections:
    - kevingstewart.f5_sslo_ansible
    
  vars: 
    provider:
      server: 10.1.1.4
      user: admin
      password: admin
      validate_certs: no
      server_port: 443

  tasks:
    - name: SSLO LAYER3 service
      bigip_sslo_service_layer3:
        provider: "{{ provider }}"
        name: "layer3_1"
        devicesTo:
          interface: "1.3"
          tag: 60
          selfIp: "198.19.64.7"
          netmask: "255.255.255.128"
        devicesFrom:
          interface: "1.3"
          tag: 70
          selfIp: "198.19.64.245"
          netmask: "255.255.255.128"
        devices: 
          - ip: "198.19.64.30"
        portRemap: 8181
      delegate_to: localhost